# Generated by Django 2.1 on 2018-10-29 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bicicleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerobicicleta', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cardinalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcioncardinalidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrpciondepartamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudgeolocalizacion', models.IntegerField()),
                ('longitudgeolocalizacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlimagen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letrauno', models.CharField(max_length=1)),
                ('bis', models.CharField(max_length=3)),
                ('letrados', models.CharField(max_length=1)),
                ('numerocalle', models.CharField(max_length=3)),
                ('letratres', models.CharField(max_length=1)),
                ('numerocomplemento', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=30)),
                ('cardinalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Cardinalidad')),
                ('cuidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroidentificacion', models.IntegerField()),
                ('nombrepropietario', models.CharField(max_length=30)),
                ('apellidopropietario', models.CharField(max_length=30)),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Localizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Tipocalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripciontipocalle', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tipoidentificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripciontipoidentificacion', models.CharField(max_length=50)),
                ('siglatipoidentificacion', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='propietario',
            name='tipoidentificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Tipoidentificacion'),
        ),
        migrations.AddField(
            model_name='localizacion',
            name='tipocalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Tipocalle'),
        ),
        migrations.AddField(
            model_name='geolocalizacion',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Propietario'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Departamento'),
        ),
        migrations.AddField(
            model_name='bicicleta',
            name='idimagen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movil.Imagen'),
        ),
    ]
